version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=stmDb
      - MYSQL_USER=dilsad
      - MYSQL_PASSWORD=dilsad123
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stmDb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: dilsad
      SPRING_DATASOURCE_PASSWORD: dilsad123
