apiVersion: v1
kind: Service
metadata:
  name: student-portal-service
spec:
  selector:
    app: student-portal-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
